export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CERRAR_SESION = "CERRAR_SESION"

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";

export const AUTH_USUARIO = "AUTH_USUARIO";
export const AUTH_USUARIO_EXITOSO = "AUTH_USUARIO_EXITOSO";
export const AUTH_USUARIO_ERROR = "AUTH_USUARIO_ERROR";

export const CREANDO_RECETA = "CREANDO_RECETA";
export const CREAR_RECETA_EXITOSO = "CREAR_RECETA_EXITOSO";
export const CREAR_RECETA_ERROR = "CREAR_RECETA_ERROR";

//RECETAS
export const OBTENIENDO_RECETAS = "OBTENIENDO_RECETAS"
export const OBTENER_RECETAS_EXITO = "OBTENER_RECETAS_EXITO"
export const OBTENER_RECETAS_ERROR = "OBTENER_RECETAS_ERROR"

export const OBTENIENDO_RECETASPOPULARES = "OBTENIENDO_RECETASPOPULARES"
export const OBTENER_RECETASPOPULARES_EXITO = "OBTENER_RECETASPOPULARES_EXITO"
export const OBTENER_RECETASPOPULARES_ERROR = "OBTENER_RECETASPOPULARES_ERROR"

export const OBTENIENDO_RECETASFAV = "OBTENIENDO_RECETASFAV"
export const OBTENER_RECETASFAV_EXITO = "OBTENER_RECETASFAV_EXITO"
export const OBTENER_RECETASFAV_ERROR = "OBTENER_RECETASFAV_ERROR"

export const OBTENIENDO_RECETAID = 'OBTENIENDO_RECETAID'
export const OBTENER_RECETAID_EXITO = 'OBTENER_RECETAID_EXITO'
export const OBTENER_RECETAID_ERROR = 'OBTENER_RECETAID_ERROR'


export const AGREGANDO_RECETAFAV = 'AGREGANDO_RECETAFAV'
export const AGREGAR_RECETAFAV_EXITO = 'AGREGAR_RECETAFAV_EXITO'
export const AGREGAR_RECETAFAV_ERROR = 'AGREGAR_RECETAFAV_ERROR'

export const ELIMINANDO_RECETA = 'ELIMINANDO_RECETA'
export const ELIMINAR_RECETA_EXITO = 'ELIMINAR_RECETA_EXITO'
export const ELIMINAR_RECETA_ERROR = 'ELIMINAR_RECETA_ERROR'

//COMENTARIOS

export const OBTENIENDO_COMENTARIOS = 'OBTENIENDO_COMENTARIOS'
export const OBTENER_COMENTARIOS_EXITO = 'OBTENER_COMENTARIOS_EXITO'
export const OBTENER_COMETARIOS_ERROR = 'OBTENER_COMETARIOS_ERROR'

export const AGREGANDO_COMENTARIO = 'AGREGANDO_COMENTARIO'
export const AGREGAR_COMENTARIO_EXITO = 'AGREGAR_COMENTARIO_EXITO'
export const AGREGAR_COMENTARIO_ERROR = 'AGREGAR_COMENTARIO_ERROR'


//BUSQUEDA DE RECETAS
export const BUSCANDO_POR_RECETA = 'BUSCANDO_POR_RECETA'
export const BUSCAR_POR_RECETA_EXITO = 'BUSCAR_POR_RECETA_EXITO'
export const BUSCAR_POR_RECETA_ERROR = 'BUSCAR_POR_RECETA_ERROR'

export const BUSCANDO_POR_INGREDIENTE = 'BUSCANDO_POR_INGREDIENTE'
export const BUSCAR_POR_INGREDIENTE_EXITO = 'BUSCAR_POR_INGREDIENTE_EXITO'
export const BUSCAR_POR_INGREDIENTE_ERROR = 'BUSCAR_POR_INGREDIENTE_ERROR'


//MOSTRAR INGREDEINTES
export const MOSTRANDO_INGREDIENTES = 'MOSTRANDO_INGREDIENTES'
export const MOSTRAR_INGREDIENTES_EXITO = 'MOSTRAR_INGREDIENTES_EXITO'
export const MOSTRAR_INGREDIENTES_ERROR = 'MOSTRAR_INGREDIENTES_ERROR'

export const AGREGANDO_INGREDIENTE = 'AGREGANDO_INGREDIENTE'
export const AGREGAR_INGREDIENTE_EXITO = 'AGREGAR_INGREDIENTE_EXITO'
export const AGREGAR_INGREDIENTE_ERROR = 'AGREGAR_INGREDIENTE_ERROR'

export const BORRAR_INGREDIENTES = 'BORRAR_INGREDIENTES'

export const CAMBIO_TIPO_BUSQUEDA = 'CAMBIO_TIPO_BUSQUEDA'
