export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";

export const AUTH_USUARIO = "AUTH_USUARIO";
export const AUTH_USUARIO_EXITOSO = "AUTH_USUARIO_EXITOSO";
export const AUTH_USUARIO_ERROR = "AUTH_USUARIO_ERROR";

export const CERRAR_SESION = "CERRAR_SESION";
